# Generated by Django 4.2 on 2023-06-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bannos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resenna',
            fields=[
                ('id_resenna', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(max_length=300)),
                ('valoracion_general', models.FloatField()),
                ('valoracion_limpieza', models.FloatField()),
                ('valoracion_utensilios', models.FloatField()),
                ('valoracion_disponibilidad', models.FloatField()),
                ('valoracion_comodidad', models.FloatField()),
                ('cantidad_de_valoracion_positiva', models.FloatField()),
                ('cantidad_de_valoracion_negativa', models.FloatField()),
                ('banno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannos.banno')),
            ],
        ),
    ]
