# Generated by Django 4.2 on 2023-06-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenna', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenna',
            name='cantidad_de_valoracion_negativa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resenna',
            name='cantidad_de_valoracion_positiva',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resenna',
            name='valoracion_comodidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resenna',
            name='valoracion_disponibilidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resenna',
            name='valoracion_limpieza',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resenna',
            name='valoracion_utensilios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
