# Generated by Django 4.2 on 2023-06-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departamento',
            field=models.CharField(choices=[('Plan Común', 'Plan Común'), ('Astronomía', 'Astronomía'), ('Física', 'Física'), ('Geofísica', 'Geofísica'), ('Geología', 'Geología'), ('Civil', 'Civil'), ('Biotecnología', 'Biotecnología'), ('Computación', 'Computación'), ('Eléctrica', 'Eléctrica'), ('Industrial', 'Industrial'), ('Matemática', 'Matemática'), ('Mecánica', 'Mecánica'), ('Minas', 'Minas'), ('Química', 'Química'), ('Magister/Doctorado', 'Magister/Doctorado')], max_length=30),
        ),
    ]
