# Generated by Django 4.2 on 2023-06-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.CharField(default='/static/media/profile1.jpg', max_length=50),
        ),
    ]
