# Generated by Django 4.2 on 2023-07-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.CharField(default='/static/img/profile1.png', max_length=50),
        ),
    ]
