# Generated by Django 4.2 on 2023-06-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.PositiveSmallIntegerField(choices=[(850, 850), (851, 851)], null=True)),
                ('edificio', models.CharField(max_length=250)),
                ('piso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Banno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No binario', 'No binario')], max_length=10)),
                ('valoracion_limpieza', models.FloatField()),
                ('valoracion_utensilios', models.FloatField()),
                ('valoracion_disponibilidad', models.FloatField()),
                ('valoracion_comodidad', models.FloatField()),
                ('valoracion_general', models.FloatField()),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannos.ubicacion')),
            ],
        ),
    ]
