# Generated by Django 4.2 on 2023-07-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannos", "0004_banno_num_resennas"),
    ]

    operations = [
        migrations.AddField(
            model_name="banno",
            name="banno_img",
            field=models.CharField(
                default="/static/assets/images/b1.jpg", max_length=50
            ),
        ),
    ]
